"""Regenerate a Clast *.JsonContext.cs from its generated Google API client .cs.

The upstream Clast transform tool is not in the repo; this reproduces its output
(validated byte-for-byte against the committed files before a sync merge).
"""
import io, sys, csparse

HEADER = """// Generated by the Clast transform. Source-generated System.Text.Json metadata plus reflection-free
// request-parameter descriptors and enum wire-string maps for this client.
using System;
using System.Runtime.CompilerServices;
using System.Text.Json.Serialization;
using Google.Apis.Util;

#if NETSTANDARD2_0
namespace System.Runtime.CompilerServices
{
    [System.AttributeUsage(System.AttributeTargets.Method, Inherited = false)]
    internal sealed class ModuleInitializerAttribute : System.Attribute { }
}
#endif

"""


def extra_serializable_lines(existing, emitted):
    """Registrations present in the committed file that aren't derivable from the client.

    e.g. the explicit IList<T> entries Bigquery.v2 needs to disambiguate two nested
    types that share a simple name. Carried over verbatim, after the derived list.
    """
    if not existing:
        return []
    with io.open(existing, encoding='utf-8-sig') as fh:
        lines = [l.rstrip() + '\n' for l in fh if l.lstrip().startswith('[JsonSerializable(')]
    have = set(l.strip() for l in emitted)
    return [l for l in lines if l.strip() not in have]


def generate(client_cs, client_ns, existing=None):
    types = csparse.parse(client_cs)
    data_ns = client_ns + '.Data'
    base_name = None
    for t in types:
        if t.ns == client_ns and t.name.endswith('BaseServiceRequest') and t.kind == 'class':
            base_name = t.name
            base_type = t
    if base_name is None:
        raise SystemExit('no base service request found in ' + client_cs)

    data_classes = sorted((t for t in types if t.ns == data_ns and t.kind == 'class'),
                          key=lambda t: t.nested.upper())
    requests = [t for t in types
                if t.ns == client_ns and t.kind == 'class'
                and (t.base.startswith(base_name + '<')
                     or t.base.startswith('Google.Apis.Upload.ResumableUpload<'))]

    out = []
    w = out.append
    w(HEADER)
    w('namespace %s\n{\n' % data_ns)
    w('    [JsonSourceGenerationOptions(DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull, '
      'NumberHandling = JsonNumberHandling.AllowReadingFromString)]\n')
    emitted = ['    [JsonSerializable(typeof(global::%s.%s), TypeInfoPropertyName = "Schema_%s")]\n'
               % (data_ns, t.nested, t.nested.replace('.', '_')) for t in data_classes]
    emitted += extra_serializable_lines(existing, emitted)
    for line in emitted:
        w(line)
    w('    internal partial class GeneratedClientJsonContext : JsonSerializerContext\n    {\n    }\n')
    w('\n#pragma warning disable CA2255 // Module initializer: this client self-registers its JSON, '
      'parameter and enum metadata.\n')
    w('#pragma warning disable CS0618  // Reading obsolete request-parameter properties mirrors the '
      'previous reflective behavior.\n')
    w('    internal static class GeneratedClientJsonModule\n    {\n')
    w('        private static RequestParameterDescriptor P(string name, RequestParameterType type, '
      'bool isValueType, Func<object, object> getter) =>\n')
    w('            new RequestParameterDescriptor(name, type, isValueType, getter);\n\n')
    w('        [ModuleInitializer]\n        internal static void Initialize()\n        {\n')
    w('            Google.Apis.Json.SystemTextJsonSerializer.RegisterTypeInfoResolver('
      'GeneratedClientJsonContext.Default);\n\n')

    for r in requests:
        full = 'global::%s.%s' % (client_ns, r.nested)
        w('            RequestParameterRegistry.Register(typeof(%s), new RequestParameterDescriptor[]\n'
          '            {\n' % full)
        # Media-upload classes redeclare the common parameters themselves; plain requests
        # inherit them from the base service request, appended after their own.
        inherits_base = r.base.startswith(base_name + '<')
        plist = list(r.params) + (list(base_type.params) if inherits_base else [])
        for wire, kind, is_vt, prop in plist:
            w('                P("%s", RequestParameterType.%s, %s, r => ((%s)r).%s),\n'
              % (wire, kind, 'true' if is_vt else 'false', full, prop))
        w('            });\n')

    w('\n')
    enums = []
    req_nested = {r.nested for r in requests}
    for t in types:
        if t.kind != 'enum' or not t.enum_members or t.ns != client_ns or len(t.path) < 2:
            continue
        parent = '.'.join(t.path[:-1])
        if parent == base_name:
            enums.append(('global::%s.%s<object>.%s' % (client_ns, base_name, t.name), t))
        elif parent in req_nested:
            enums.append(('global::%s.%s' % (client_ns, t.nested), t))
    for full, t in enums:
        w('            EnumStringValueRegistry.Register(typeof(%s), value =>\n            {\n' % full)
        w('                switch (value.ToString())\n                {\n')
        for member, wire in t.enum_members:
            w('                    case "%s": return "%s";\n' % (member, wire))
        w('                    default: return value.ToString();\n                }\n            });\n')

    w('        }\n    }\n#pragma warning restore CS0618\n#pragma warning restore CA2255\n}\n')
    return ''.join(out)


if __name__ == '__main__':
    client_cs, client_ns, dest = sys.argv[1], sys.argv[2], sys.argv[3]
    existing = sys.argv[4] if len(sys.argv) > 4 else None
    text = generate(client_cs, client_ns, existing)
    io.open(dest, 'w', encoding='utf-8-sig', newline='\r\n').write(text)
